CREATE TABLE NHANVIEN(
    MaNV CHAR(5) NOT NULL PRIMARY KEY,
    HoTen VARCHAR2(30),
    GioiTinh VARCHAR2(10),
    CMND NUMBER,
    DiaChi VARCHAR2(50),
    Email VARCHAR2(30),
    SDT NUMBER,
    MaPB CHAR(4)
);

CREATE TABLE PHONGBAN(
    MaPB CHAR(5) NOT NULL PRIMARY KEY,
    TenPB VARCHAR2(30),
    SoLuongNV NUMBER,
    TruongPB CHAR(5)
);

CREATE TABLE SANPHAM(
    MaSP CHAR(5) NOT NULL PRIMARY KEY,
    TenSP VARCHAR2(30),
    DonVi VARCHAR2(10),
    SoLuong NUMBER,
    DonGia NUMBER,
    TGBH DATE,
    MaLoai CHAR(5)
);

CREATE TABLE PHANLOAI(
    MaLoai CHAR(5) NOT NULL PRIMARY KEY,
    TenLoai VARCHAR2(20)
);

CREATE TABLE KHUYENMAI(
    MaKM CHAR(5) NOT NULL PRIMARY KEY,
    NgayBD DATE,
    NgayKT DATE,
    PhanTramKM NUMBER
);

CREATE TABLE NHACUNGCAP(
    MaNCC CHAR(5) NOT NULL PRIMARY KEY,
    TenNCC VARCHAR2(30),
    DiaChi VARCHAR2(30),
    Email VARCHAR2(30),
    SDT NUMBER
);

CREATE TABLE KHACHHANG(
    MaKH CHAR(5) NOT NULL PRIMARY KEY,
    TenKH VARCHAR2(30),
    DiaChi VARCHAR2(30),
    SDT NUMBER
);

CREATE TABLE NHAPHANG(
    MaNH CHAR(5) NOT NULL PRIMARY KEY,
    NgayNH DATE,
    SoTien NUMBER,
    MaNCC CHAR(5),
    MaNV CHAR(5)
);

CREATE TABLE CTNH(
    MaNH CHAR(5),
    MaSP CHAR(5),
    SoLuong NUMBER,
    TongTienNhap NUMBER,
    MaKM CHAR(5)
);

CREATE TABLE HD_MUASP(
    SoHD CHAR(5) NOT NULL PRIMARY KEY,
    NgayLapHD DATE,
    TriGia NUMBER,
    MaKH CHAR(5),
    MaNV CHAR(5)
);

CREATE TABLE CTHD_MUASP(
    SoHD CHAR(5),
    MaSP CHAR(5),
    SoLuong NUMBER,
    TongTien NUMBER,
    MaKM CHAR(5)
);

CREATE TABLE PHIEUBAOHANH(
    MaPBH CHAR(5) NOT NULL PRIMARY KEY,
    NgayHetHan DATE,
    MaSP CHAR(5)
);

CREATE TABLE BAOHANHSP(
    MaBH CHAR(5) NOT NULL PRIMARY KEY,
    NgayBH DATE,
    MoTaLoi VARCHAR2(30),
    SoHD CHAR(5)
);

CREATE TABLE DANGNHAP(
    TenDN VARCHAR2(20) NOT NULL PRIMARY KEY,
    MatKhau VARCHAR2(20),
    MaNV CHAR(5)
);

--KHOA NGOAI
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_NV FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB);
ALTER TABLE SANPHAM ADD CONSTRAINT FK_SP FOREIGN KEY (MaLoai) REFERENCES PHANLOAI(MaLoai);
ALTER TABLE NHAPHANG ADD CONSTRAINT FK1_NH FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);
ALTER TABLE NHAPHANG ADD CONSTRAINT FK2_NH FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);
ALTER TABLE CTNH ADD CONSTRAINT FK1_CTNH FOREIGN KEY (MaNH) REFERENCES NHAPHANG(MaNH);
ALTER TABLE CTNH ADD CONSTRAINT FK2_CTNH FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);
ALTER TABLE CTNH ADD CONSTRAINT FK3_CTNH FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);
ALTER TABLE HD_MUASP ADD CONSTRAINT FK1_MUASP FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);
ALTER TABLE HD_MUASP ADD CONSTRAINT FK2_MUASP FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);
ALTER TABLE CTHD_MUASP ADD CONSTRAINT FK1_CTMSP FOREIGN KEY (SoHD) REFERENCES HD_MUASP(SoHD);
ALTER TABLE CTHD_MUASP ADD CONSTRAINT FK2_CTMSP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);
ALTER TABLE CTHD_MUASP ADD CONSTRAINT FK3_CTMSP FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);
ALTER TABLE PHIEUBAOHANH ADD CONSTRAINT FK_PBH FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);
ALTER TABLE BAOHANHSP ADD CONSTRAINT FK_BH FOREIGN KEY (SoHD) REFERENCES HD_MUASP(SoHD);
ALTER TABLE DANGNHAP ADD CONSTRAINT FK_DN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

