
-- BANG PHIEU BAO HANH SAN PHAM

CREATE TABLE BAOHANHSP(
    MaBH CHAR(5) NOT NULL PRIMARY KEY,
    NgayBH DATE,
    MoTaLoi VARCHAR2(30),
    SoHD CHAR(5)
);

-- KHOA NGOAI LIEN QUAN
ALTER TABLE BAOHANHSP ADD CONSTRAINT FK_BH FOREIGN KEY (SoHD) REFERENCES HD_MUASP(SoHD);