
-- BANG CHI TIET MUA SAN PHAM

CREATE TABLE CTHD_MUASP(
    SoHD CHAR(5),
    MaSP CHAR(5),
    SoLuong NUMBER,
    TongTien NUMBER,
    MaKM CHAR(5)
);

-- KHOA NGOAI LIEN QUAN
ALTER TABLE CTHD_MUASP ADD CONSTRAINT FK1_CTMSP FOREIGN KEY (SoHD) REFERENCES HD_MUASP(SoHD);
ALTER TABLE CTHD_MUASP ADD CONSTRAINT FK2_CTMSP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);
ALTER TABLE CTHD_MUASP ADD CONSTRAINT FK3_CTMSP FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);