-- BANG CHI TIET NHAP HANG

CREATE TABLE CTNH(
    MaNH CHAR(5),
    MaSP CHAR(5),
    SoLuong NUMBER,
    TongTienNhap NUMBER,
    MaKM CHAR(5)
);

--KHOA NGOAI LIEN QUAN
ALTER TABLE CTNH ADD CONSTRAINT PK1_CTNH FOREIGN KEY (MaNH) REFERENCES NHAPHANG(MaNH);
ALTER TABLE CTNH ADD CONSTRAINT PK2_CTNH FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);
ALTER TABLE CTNH ADD CONSTRAINT PK3_CTNH FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);