
-- BANG DANG NHAP

CREATE TABLE DANGNHAP(
    TenDN VARCHAR2(20) NOT NULL PRIMARY KEY,
    MatKhau VARCHAR2(20),
    MaNV CHAR(5)
);

-- KHOA NGOAI LIEN QUAN
ALTER TABLE DANGNHAP ADD CONSTRAINT FK_DN FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);