-- BANG CHI TIET HOA DON MUA SAN PHAM

CREATE TABLE HD_MUASP(
    SoHD CHAR(5) NOT NULL PRIMARY KEY,
    NgayLapHD DATE,
    TriGia NUMBER,
    MaKH CHAR(5),
    MaNV CHAR(5)
);

-- KHOA NGOAI LIEN QUAN

ALTER TABLE HD_MUASP ADD CONSTRAINT PK1_MUASP FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);
ALTER TABLE HD_MUASP ADD CONSTRAINT PK2_MUASP FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);