--CHI TIET BANG KHACH HANG

CREATE TABLE KHACHHANG(
    MaKH CHAR(5) NOT NULL PRIMARY KEY,
    TenKH VARCHAR2(30),
    DiaChi VARCHAR2(30),
    SDT NUMBER
);
--KHOA NGOAI LIEN QUAN
ALTER TABLE HD_MUASP ADD CONSTRAINT PK1_MUASP FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);