
--CHI TIET BAN KHUYEN MAI
CREATE TABLE KHUYENMAI(
    MaKM CHAR(5) NOT NULL PRIMARY KEY,
    NgayBD DATE,
    NgayKT DATE,
    PhanTramKM NUMBER
);
--KHOA NGOAI LIEN QUAN
ALTER TABLE CTNH ADD CONSTRAINT PK3_CTNH FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);
ALTER TABLE CTHD_MUASP ADD CONSTRAINT PK3_CTMSP FOREIGN KEY (MaKM) REFERENCES KHUYENMAI(MaKM);
