--CHI TIET BANG NHA CUNG CAP
 CREATE TABLE NHACUNGCAP(
    MaNCC CHAR(5) NOT NULL PRIMARY KEY,
    TenNCC VARCHAR2(30),
    DiaChi VARCHAR2(30),
    SDT NUMBER
);
--KHOA NGOAI LIEN QUAN
ALTER TABLE NHAPHANG ADD CONSTRAINT PK1_NH FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);
