--BANG NHAN VIEN
CREATE TABLE NHANVIEN(
    MaNV CHAR(5) NOT NULL PRIMARY KEY,
    HoTen VARCHAR2(30),
    GioiTinh VARCHAR2(10),
    CMND NUMBER,
    DiaChi VARCHAR2(50),
    Email VARCHAR2(30),
    SDT NUMBER,
    MaPB CHAR(4)
);
--KHOA NGOAI LIEN QUAN
ALTER TABLE NHANVIEN ADD CONSTRAINT PK_NV FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB);
