-- BANG NHAP HANG

CREATE TABLE NHAPHANG(
    MaNH CHAR(5) NOT NULL PRIMARY KEY,
    NgayNH DATE,
    SoTien NUMBER,
    MaNCC CHAR(5),
    MaNV CHAR(5)
);

--KHOA NGOAI LIEN QUAN

ALTER TABLE NHAPHANG ADD CONSTRAINT PK1_NH FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC);
ALTER TABLE NHAPHANG ADD CONSTRAINT PK2_NH FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);