--CHI TIET BANG PHAN LOAI

CREATE TABLE PHANLOAI(
    MaLoai CHAR(5) NOT NULL PRIMARY KEY,
    TenLoai VARCHAR2(20)
);
--KHOA NGOAI LIEN QUAN
ALTER TABLE SANPHAM ADD CONSTRAINT PK_SP FOREIGN KEY (MaLoai) REFERENCES PHANLOAI(MaLoai);