
-- BANG PHIEU BAO HANH

CREATE TABLE PHIEUBAOHANH(
    MaPBH CHAR(5) NOT NULL PRIMARY KEY,
    NgayHetHan DATE,
    MaSP CHAR(5)
);

-- KHOA NGOAI LIEN QUAN
ALTER TABLE PHIEUBAOHANH ADD CONSTRAINT FK_PBH FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);