-- BANG SAN PHAM
CREATE TABLE SANPHAM(
    MaSP CHAR(5) NOT NULL PRIMARY KEY,
    TenSP VARCHAR2(30),
    DonVi VARCHAR2(10),
    SoLuong NUMBER,
    DonGia NUMBER,
    TGBH DATE,
    MaLoai CHAR(5)
);
--KHOA NGOAI LIEN QUAN
ALTER TABLE SANPHAM ADD CONSTRAINT PK_SP FOREIGN KEY (MaLoai) REFERENCES PHANLOAI(MaLoai);